global:
  configMapName: eazybankprod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8084/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"
  otelExporterEndPoint: http://tempo.default.svc.cluster.local:4318
  otelMetricsExporter: none
  otelLogsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
  accountsDatasourceUrl: "jdbc:mysql://accountsdb:3306/accountsdb"
  cardsDatasourceUrl: "jdbc:mysql://cardsdb:3308/cardsdb"
  loansDatasourceUrl: "jdbc:mysql://loansdb:3307/loansdb"
  datasourceUsername: "root"
  datasourcePassword: "root"
  mysqlRootPassword: "root"
  mysqlDatabaseAccounts: "accountsdb"
  mysqlDatabaseCards: "cardsdb"
  mysqlDatabaseLoans: "loansdb"
