# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: dheerajbr46/accounts
  tag: s14

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
database_enabled: true
datasourceUrlKey: ACCOUNTS_SPRING_DATASOURCE_URL