apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-prometheus.fullname" . }}
  labels:
    {{ include "kube-prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval }}

    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['accounts.default.svc.cluster.local:8081']
      - job_name: 'loans'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['loans.default.svc.cluster.local:8083']
      - job_name: 'cards'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['cards.default.svc.cluster.local:8082']
      - job_name: 'gatewayserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['gatewayserver.default.svc.cluster.local:8072']
      - job_name: 'eurekaserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eurekaserver.default.svc.cluster.local:8070']
      - job_name: 'configserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['configserver.default.svc.cluster.local:8084']
