build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Dave Doe - Developer"
    email: "dave@eazybank.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345