# Default values for cards-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storage:
  size: 700Mi
  accessMode: ReadWriteOnce

image:
  repository: mysql
  tag: "8.0"

containerPort: 3308

service:
  name: cardsdb
  type: ClusterIP
  port: 3308
  targetPort: 3308

databaseKey: MYSQL_DATABASE_CARDS
