apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8084/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  EUREKA_APPLICATION_NAME: "eurekaserver"
  ACCOUNTS_APPLICATION_NAME: "accounts"
  LOANS_APPLICATION_NAME: "loans"
  CARDS_APPLICATION_NAME: "cards"
  GATEWAY_APPLICATION_NAME: "gatewayserver"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  ACCOUNTS_SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
  LOANS_SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3307/loansdb"
  CARDS_SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  
  MYSQL_DATABASE_ACCOUNTS: "accountsdb"
  MYSQL_DATABASE_LOANS: "loansdb"
  MYSQL_DATABASE_CARDS: "cardsdb"
  MYSQL_ROOT_PASSWORD: "root"
  