# Default values for loans-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storage:
  size: 700Mi
  accessMode: ReadWriteOnce

image:
  repository: mysql
  tag: "8.0"

containerPort: 3307

service:
  name: loansdb
  type: ClusterIP
  port: 3307
  targetPort: 3307

databaseKey: MYSQL_DATABASE_LOANS
